spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.rcfbxrdwlnswkyydxiio
spring.datasource.password=Rodript2005.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8081
spring.thymeleaf.cache=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rodrigocar2005@gmail.com
spring.mail.password=ytnypgdpcumlkend
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=rodrigocar2005@gmail.com